version: '3'
services:
  database:
    image: mysql:5.7
    container_name: sakila-database
    volumes:
        - dbdata:/var/lib/mysql
    restart: on-failure
    ports:
        - "3306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=1q2w3e4r
volumes:
    dbdata:
        driver: local